const popular_parties = [{
        name: "Friends",
        price: "330 $",
        about: `Have you always dreamed of visiting that same cafe from your favorite TV series? Then come to us soon! The "Friends" room fully conveys the atmosphere of a sitcom. Here you can chat about everything in the world, eat a hot pie while listening to Phoebe's funny songs, or have a wild party in the style of the most famous TV series of the 90s.`,
        people: "Up to 29 people",
        space: "58 sq. m",
        img: "./image/friends.jpg",
    },
    {
        name: "Tahiti",
        price: "210 $",
        about: `The philosophy of the locals - “aita pea pea” - means “don’t worry”, and in this room you can completely relax and have a great time with your company, without worrying about anything!`,
        people: "Up to 19 people",
        space: "35 sq. m",
        img: "./image/tahiti.jpg",
    },
    {
        name: "Chicago",
        price: "200 $",
        about: `A gangster party in the style of the 20s, a bohemian get-together in an art salon, a wild party in a jazz club or blues under the lights of skyscrapers - Chicago gives thousands of opportunities for those who like to rock hard. We have conveyed the entire atmosphere of the American metropolis, then it’s only up to your imagination!`,
        people: "Up to 17 people",
        space: "31 sq. m",
        img: "./image/chicago.jpg",
    },
];

const parties = [{
        name: "Friends",
        price: "330 $",
        about: `Have you always dreamed of visiting that same cafe from your favorite TV series? Then come to us soon! The "Friends" room fully conveys the atmosphere of a sitcom. Here you can chat about everything in the world, eat a hot pie while listening to Phoebe's funny songs, or have a wild party in the style of the most famous TV series of the 90s.`,
        people: "Up to 29 people",
        space: "58 sq. m",
        img: "./image/friends.jpg",
    },
    {
        name: "Retrouve",
        price: "150 $",
        about: `Where are the brightest parties? In "Retrouve"! Gather your friends and throw a neon party with the soundtracks of your favorite old movies and video games!`,
        people: "Up to 10 people",
        space: "21 sq. m",
        img: "./image/retrouve.jpg",
    },
    {
        name: "Tahiti",
        price: "210 $",
        about: `The philosophy of the locals - “aita pea pea” - means “don’t worry”, and in this room you can completely relax and have a great time with your company, without worrying about anything!`,
        people: "Up to 19 people",
        space: "35 sq. m",
        img: "./image/tahiti.jpg",
    },
    {
        name: "Street art",
        price: "130 $",
        about: `For connoisseurs of contemporary art and street art Banksy. For hip-hop fans and skateboard kings. For lovers of urban and recreation without stereotypical restrictions!`,
        people: "Up to 9 people",
        space: "16 sq. m",
        img: "./image/streetart.jpg",
    },
    {
        name: "Chicago",
        price: "200 $",
        about: `A gangster party in the style of the 20s, a bohemian get-together in an art salon, a wild party in a jazz club or blues under the lights of skyscrapers - Chicago gives thousands of opportunities for those who like to rock hard. We have conveyed the entire atmosphere of the American metropolis, then it’s only up to your imagination!`,
        people: "Up to 17 people",
        space: "31 sq. m",
        img: "./image/chicago.jpg",
    },
    {
        name: "Boho",
        price: "150 $",
        about: `"Boho" is a room with a spirit of freedom and creativity, combining classic, glamor and eco. It is ideal for cozy evenings with friends, romantic dates, hen parties, master classes and much more.`,
        people: "Up to 10 people",
        space: "19 sq. m",
        img: "./image/boho.jpg",
    },
    {
        name: "Lagoon",
        price: "350 $",
        about: `Come with your friends to Laguna and have fun! Throw the coolest sea party!`,
        people: "Up to 23 people",
        space: "32   sq. m",
        img: "./image/lagoon.jpg",
    },
    {
        name: "Masonic lodge",
        price: "250 $",
        about: `Aristocratic, expensive, serious. Here you can come up with conspiracies or simply draw triangles. `,
        people: "Up to 15 people",
        space: "30   sq. m",
        img: "./image/masoniclodge.jpg",
    },

    {
        name: "Tokyo",
        price: "280 $",
        about: `Progressive, super-technological, innovative, it's all about Tokyo! A city that leaves no one indifferent, a city with its own culture and style, a city for your party. `,
        people: "Up to 15 people",
        space: "25   sq. m",
        img: "./image/tokyo.jpg",
    },
];